parameters:
    audio_server_base_url: '%env(AUDIO_SERVER_URL)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'

    App\Service\SongGenerator\LocaleDataProvider:
        arguments:
            $projectDir: '%kernel.project_dir%'

    App\Service\Audio\AudioClient:
        arguments:
            $baseUrl: '%audio_server_base_url%'
